import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {gzipSync} from 'node:zlib';
import {output,aliases} from './build.mjs';
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.mp4':'video/mp4','.webm':'video/webm','.vtt':'text/vtt; charset=utf-8','.xml':'application/xml','.txt':'text/plain; charset=utf-8'};
export const headers={'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; media-src 'self'; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'none'"};
export function createServer(){return http.createServer((req,res)=>{for(const[k,v]of Object.entries(headers))res.setHeader(k,v);let url;try{url=decodeURIComponent(new URL(req.url,'http://localhost').pathname)}catch{res.writeHead(400);res.end();return}if(!['GET','HEAD'].includes(req.method)){res.writeHead(405,{'Allow':'GET, HEAD'});res.end();return}if(aliases[url]){res.writeHead(308,{'Location':aliases[url]});res.end();return}if(url.endsWith('.html')&&url!=='/404.html'){res.writeHead(308,{'Location':url==='/index.html'?'/':url.slice(0,-5)});res.end();return}if(url.length>1&&url.endsWith('/')){res.writeHead(308,{'Location':url.slice(0,-1)});res.end();return}let file=path.resolve(output,'.'+(url==='/'?'/index.html':url));if(!file.startsWith(output+path.sep)){res.writeHead(403);res.end();return}if(!path.extname(file))file+='.html';let status=200;if(!fs.existsSync(file)||!fs.statSync(file).isFile()){file=path.join(output,'404.html');status=404}const type=types[path.extname(file)]||'application/octet-stream';res.setHeader('Content-Type',type);res.setHeader('Cache-Control','no-cache');if(!fs.existsSync(file)){res.writeHead(503);res.end('Run npm run build first.');return}const data=fs.readFileSync(file);const range=req.headers.range;if(range&&status===200&&/^video/.test(type)){const match=/^bytes=(\d+)-(\d*)$/.exec(range);if(!match){res.writeHead(416,{'Content-Range':`bytes */${data.length}`});res.end();return}const start=Number(match[1]),end=match[2]?Math.min(Number(match[2]),data.length-1):data.length-1;if(start>end||start>=data.length){res.writeHead(416,{'Content-Range':`bytes */${data.length}`});res.end();return}res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${data.length}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});res.end(req.method==='HEAD'?undefined:data.subarray(start,end+1));return}let body=data;if(/text|javascript|svg|xml/.test(type)&&req.headers['accept-encoding']?.includes('gzip')){body=gzipSync(data);res.setHeader('Content-Encoding','gzip');res.setHeader('Vary','Accept-Encoding')}res.writeHead(status,{'Content-Length':body.length,'Accept-Ranges':'bytes'});res.end(req.method==='HEAD'?undefined:body)})}
if(process.argv[1]===fileURLToPath(import.meta.url)){const port=Number(process.env.PORT||8080);createServer().listen(port,'127.0.0.1',()=>console.log(`BundleBoB is running at http://127.0.0.1:${port}`));}
