import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {gzipSync} from 'node:zlib';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const base=process.env.TEST_URL||'http://127.0.0.1:8080';
const output=path.join(root,'audit');await fs.mkdir(path.join(output,'screenshots'),{recursive:true});
const routes=['/services','/approach','/','/how-it-works','/solutions','/why-bundlebob','/resources','/resources/when-systems-disagree','/resources/wip-review','/resources/mapping-first','/about','/contact','/system'];
const results={pages:[],links:[],interactions:{},motion:{},video:{},errors:[],externalRequests:[]};
const browser=await chromium.launch({...(process.env.CHROME_CHANNEL?{channel:process.env.CHROME_CHANNEL}:{})});
const links=new Set();
for(const theme of ['light','dark'])for(const width of [1440,390]){
 const context=await browser.newContext({viewport:{width,height:900},colorScheme:theme,reducedMotion:'no-preference'});
 const page=await context.newPage();
 page.on('pageerror',e=>results.errors.push({page:page.url(),error:e.message}));
 page.on('console',m=>{if(m.type()==='error')results.errors.push({page:page.url(),error:m.text()})});
 page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('blob:'))results.externalRequests.push(r.url())});
 for(const route of routes){await page.goto(base+route,{waitUntil:'networkidle'});await page.waitForTimeout(200);const check=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,h1:document.querySelectorAll('h1').length,theme:document.documentElement.dataset.theme,mainWords:document.querySelector('main').innerText.split(/\s+/).length,headingsClipped:[...document.querySelectorAll('h1,h2,h3')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&(r.left< -1||r.right>innerWidth+1)&&!e.closest('.capability-rail')}).map(e=>e.textContent)}));results.pages.push({route,theme,width,...check});if(check.scrollWidth>width||check.h1!==1||check.headingsClipped.length)results.errors.push({route,theme,width,layout:check});for(const a of await page.locator('a[href]').evaluateAll(es=>es.map(e=>e.getAttribute('href'))))if(a.startsWith('/')||a.startsWith('#'))links.add(new URL(a,base+route).href);await page.screenshot({path:path.join(output,'screenshots',`${route==='/'?'home':route.slice(1).replaceAll('/','-')}-${width}-${theme}.png`),fullPage:true});}
 await context.close();
}
const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();
for(const href of links){const u=new URL(href);const response=await page.request.get(u.origin+u.pathname);let anchor=true;if(u.hash){await page.goto(u.origin+u.pathname);anchor=await page.locator('[id]').evaluateAll((es,id)=>es.some(e=>e.id===id),u.hash.slice(1))}results.links.push({url:u.pathname+u.hash,status:response.status(),anchor});if(response.status()!==200||!anchor)results.errors.push({link:u.pathname+u.hash,status:response.status(),anchor})}
await page.goto(base+'/');
const problem=page.locator('.problem-choice').nth(1);await problem.locator('summary').focus();await page.keyboard.press('Enter');results.interactions.problemKeyboard=await problem.evaluate(e=>e.open);
const explanation=page.locator('.demo-explanation');await explanation.locator('summary').click();results.interactions.demoExplanation=await explanation.evaluate(e=>e.open);
await page.setViewportSize({width:390,height:844});await page.goto(base+'/');await page.locator('.menu-toggle').click();results.interactions.mobileMenu=await page.locator('#mobile-menu').isVisible();await page.keyboard.press('Escape');results.interactions.mobileEscape=await page.locator('#mobile-menu').isHidden()&&await page.locator('.menu-toggle').evaluate(e=>document.activeElement===e);
await page.goto(base+'/resources');await page.locator('#resource-search').fill('nonexistent-topic-123');results.interactions.searchEmpty=await page.locator('#resource-empty').isVisible();await page.locator('#resource-search').fill('');results.interactions.searchReset=await page.locator('#resource-list article:visible').count()===3;
await page.goto(base+'/contact');await page.locator('[type=submit]').click();results.interactions.invalidForm=await page.locator('#name').evaluate(e=>e.getAttribute('aria-invalid')==='true'&&document.activeElement===e);await page.locator('#name').fill('Test visitor');await page.locator('#company').fill('Example workshop');await page.locator('#email').fill('visitor@example.invalid');await page.locator('#message').fill('We need a shared picture of parts, labor, and unbilled work.');const submitted=[];page.on('request',r=>{if(r.method()==='POST')submitted.push(r.url())});await page.locator('[type=submit]').click();await page.locator('#inquiry-result').waitFor();const download=page.waitForEvent('download');await page.locator('#inquiry-download').click();await(await download).saveAs(path.join(output,'inquiry-example.txt'));results.interactions.inquiryDownload=(await fs.readFile(path.join(output,'inquiry-example.txt'),'utf8')).includes('Example workshop');results.interactions.noUnintendedSubmission=submitted.length===0;
await page.goto(base+'/how-it-works');const v=page.locator('video');await v.scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('video').readyState>=1);for(const ext of ['mp4','webm']){results.video[ext]=await v.evaluate(async(v,ext)=>{v.pause();v.src='/assets/video/reconciliation.'+ext;v.load();await new Promise((resolve,reject)=>{if(v.readyState>=1)return resolve();v.addEventListener('loadedmetadata',resolve,{once:true});v.addEventListener('error',()=>reject(new Error('Video failed to load')),{once:true})});await v.play();await new Promise((resolve,reject)=>{const stop=setTimeout(()=>reject(new Error('Playback did not advance')),5000);const check=()=>{if(v.currentTime>.1){clearTimeout(stop);v.removeEventListener('timeupdate',check);resolve()}};v.addEventListener('timeupdate',check);check()});v.pause();return{duration:v.duration,width:v.videoWidth,height:v.videoHeight,played:v.currentTime>0}},ext)}
await page.goto(base+'/');await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(1000);const session=await context.newCDPSession(page);await session.send('Performance.enable');const before=await session.send('Performance.getMetrics');await page.waitForTimeout(3000);const after=await session.send('Performance.getMetrics');const metric=(r,n)=>r.metrics.find(m=>m.name===n).value;results.motion.idleTaskPercent=(metric(after,'TaskDuration')-metric(before,'TaskDuration'))/(metric(after,'Timestamp')-metric(before,'Timestamp'))*100;
await context.close();const reduced=await browser.newContext({reducedMotion:'reduce',viewport:{width:390,height:844}});const r=await reduced.newPage();await r.goto(base+'/');results.motion.reduced=await r.evaluate(()=>({sculptureStatic:getComputedStyle(document.querySelector('.sculpture-object')).transitionDuration==='0s',counts:[...document.querySelectorAll('[data-count]')].map(e=>e.textContent),animated:document.getAnimations().filter(a=>a.playState==='running').length}));await r.goto(base+'/how-it-works');await r.locator('video').scrollIntoViewIfNeeded();results.motion.reducedVideoPaused=await r.locator('video').evaluate(v=>v.paused&&!v.autoplay);await reduced.close();
const blocked=await browser.newContext();const p=await blocked.newPage();await p.route('**/assets/site.js',r=>r.abort());await p.goto(base+'/');results.motion.scriptFailureContent=await p.evaluate(()=>({mainText:document.querySelector('main').innerText.length,hiddenHeadings:[...document.querySelectorAll('main h1,main h2,main h3')].filter(e=>getComputedStyle(e).opacity==='0').length}));await blocked.close();await browser.close();
results.payload={javascriptGzip:0,javascriptRaw:0};for(const file of ['site.js','theme.js']){const data=await fs.readFile(path.join(root,'assets',file));results.payload.javascriptGzip+=gzipSync(data).length;results.payload.javascriptRaw+=data.length;}
await fs.writeFile(path.join(output,'browser-results.json'),JSON.stringify(results,null,2));
console.log(JSON.stringify({...results,pages:`${results.pages.length} page/theme/viewport combinations`,links:`${results.links.length} local links checked`},null,2));
if(results.errors.length||Object.values(results.interactions).some(v=>v===false)||Object.values(results.video).some(v=>!v.played))process.exitCode=1;
