import type { Metadata } from "next";
import Link from "next/link";
import Pending from "@/components/Pending";

export const metadata: Metadata = {
  title: "Security & data",
  description:
    "How a client firm's accounting, job-cost, and subcontractor data is isolated, stored, accessed, and handled — stated plainly, including what is not in place yet.",
};

const SECTIONS = [
  {
    h: "Tenancy and isolation",
    intro:
      "Each client firm's data is kept separate from every other client's — in storage, in processing, and in anything an AI model sees. Nothing built or learned for one firm is reused in another firm's context, prompts, or reports.",
    pending:
      "the concrete isolation model — e.g. a separate database (or separate schema) per client, per-client storage buckets, and per-client credentials — and confirmation that no shared prompt or log path mixes two clients' data.",
  },
  {
    h: "Encryption",
    intro: "Client data is encrypted in transit and at rest.",
    pending:
      "the specifics: TLS version for data in transit, encryption standard and key management for data at rest, and where the data physically resides (cloud provider and region).",
  },
  {
    h: "Access — who can see what",
    intro:
      "Access is limited to the embedded engineer assigned to your firm and named individuals who support them. Access is least-privilege and logged.",
    pending:
      "the real list: which roles can read client financial data, how access is granted and revoked, whether access is logged and reviewable by the client, and your policy on using client data for any internal purpose (default answer should be: we do not).",
  },
  {
    h: "AI and your data",
    intro:
      "Figures shown to you are computed from your source records, not generated by a model. Where an LLM is used to draft answers or summaries, it runs against your isolated data only, and its output is reviewed before anyone acts on it.",
    pending:
      "which model providers are used, whether any client data leaves your tenant to reach them, whether prompts and outputs are retained by the provider, and whether you can opt a data category out of model processing entirely.",
  },
  {
    h: "What is not in place yet",
    intro:
      "This buyer reads silence as evasion, so we state the gaps directly.",
    pending:
      "an honest list — e.g. “no SOC 2 report today; targeting [date]”, “no third-party penetration test yet”, “no formal BAA” — paired with what IS true instead (written policies, the isolation model above, background checks, whatever applies).",
  },
  {
    h: "If an engagement ends",
    intro:
      "You keep what was built. Your data is returned or destroyed on your instruction.",
    pending:
      "the actual offboarding terms: format your data is returned in, deletion timeline and confirmation, what documentation and code transfers to you, and how long any backups persist afterward.",
  },
];

export default function Security() {
  return (
    <>
      <section className="rule-b">
        <div className="container py-16 md:py-24">
          <p className="label">Security &amp; data</p>
          <h1 className="mt-5 max-w-[24ch] text-[36px] leading-tight md:text-[48px]">
            We will be inside your accounting and subcontractor data. Here is how that is handled.
          </h1>
          <p className="mt-6 lead">
            This page is written to be checkable. Where a control is real, it is
            stated plainly. Where it is not in place yet, that is stated too, next
            to what is true instead.
          </p>
        </div>
      </section>

      {SECTIONS.map((s) => (
        <section key={s.h} className="rule-b">
          <div className="container grid gap-6 py-12 md:grid-cols-[16rem_1fr] md:py-16">
            <h2 className="text-[20px]">{s.h}</h2>
            <div className="max-w-prose prose-block">
              <p className="text-ink-soft">{s.intro}</p>
              <Pending block>{s.pending}</Pending>
            </div>
          </div>
        </section>
      ))}

      <section>
        <div className="container py-16 md:py-20">
          <h2 className="max-w-[24ch] text-[24px] md:text-[30px]">
            Send us your security questionnaire. We would rather answer it before you ask than after.
          </h2>
          <div className="mt-8">
            <Link href="/contact" className="btn">
              Contact
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
